stages:
  - test
  - build
  - deploy


variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

test_app:
  image: python:3.14
  stage: test
  script:
    - pip install uv
    - uv sync
    - uv run pytest

build_image:
  image: docker:24.0.5
  stage: build
  services:
    - docker:24.0.5-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - main
deploy_gcp:
  image: alpine:latest
  stage: deploy
  before_script:

    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan $GCP_SERVER_IP >> ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts
  script:

    - ssh $GCP_USERNAME@$GCP_SERVER_IP "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh $GCP_USERNAME@$GCP_SERVER_IP "docker pull $IMAGE_TAG"
    - ssh $GCP_USERNAME@$GCP_SERVER_IP "docker stop cv-app || true"
    - ssh $GCP_USERNAME@$GCP_SERVER_IP "docker rm cv-app || true"

    - ssh $GCP_USERNAME@$GCP_SERVER_IP "docker run -d --name cv-app -p 80:8000 $IMAGE_TAG"
  only:
    - main