stages:
  - test
  - build
  - deploy


variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

test_app:
  image: python:3.14
  stage: test
  script:
    - apt-get update && apt-get install -y libgl1 libglib2.0-0
    - pip install uv
    - uv sync
    - uv run pytest

build_image:
  image: docker:24.0.5
  stage: build
  services:
    - docker:24.0.5-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master